name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    #- name: Install emulator dependencies
    #  run: sdkmanager --install "system-images;android-30;google_apis;x86"
    #- name: Create AVD
    #  run: echo no | avdmanager create avd --force --name emulator --package "system-images;android-30;google_apis;x86"
    #- name: Start AVD in the background
    #  run: $ANDROID_HOME/emulator/emulator -avd emulator -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot -no-window -camera-back none
    #- name: Wait for AVD to boot
    #  run: adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done; input keyevent 82'

    - name: Grant execute permission for gradlew (assemble_instrumented_tests_script)
      run: | 
        chmod +x gradlew 
        ./gradlew assembleDebugAndroidTest

    - name: Disable animations script
      run: |
        adb shell settings put global window_animation_scale 0.0
        adb shell settings put global transition_animation_scale 0.0
        adb shell settings put global animator_duration_scale 0.0
        
    - name: Screen record background script
      run: for n in $(seq 1 20); do adb exec-out screenrecord --time-limit=180 --output-format=h264 - > $n.h264; done
      
    - name: Check script
      run: ./gradlew check connectedCheck
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Wait for screen record to finish
      run: |
        pkill -2 -x adb
        sleep 2
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-test-results
        path: |
          *.h264
          ./app/build/reports/lint-results-debug.xml
          ./app/build/test-results/**/*.xml
          ./app/build/outputs/**/*.xml
     
